<?php
App::uses('AppModel', 'Model');

/**
 * Class TransportBillDetailedRidesManagementComponent
 * @package App\Controller\Component
 * @property TransportBillDetailedRides $TransportBillDetailedRides
 * @property TransportBillDetailRides $TransportBillDetailRides
 * @property Product $Product
 * @property Parameter $Parameter
 * @property SheetRideDetailRidesTransportBills $SheetRideDetailRidesTransportBills
 * @property SheetRideDetailRides $SheetRideDetailRides
 */
class DeleteTransportBillsManagementComponent extends Component
{
    public function initialize(Controller $controller)
    {
        parent::initialize($controller); // TODO: Change the autogenerated stub
        $this->TransportBillDetailedRides = ClassRegistry::init('TransportBillDetailedRides');
        $this->Product = ClassRegistry::init('Product');
    }

    public function updateSheetRideDetailRideStatusId($transportBillId, $type)
    {
        $this->SheetRideDetailRidesTransportBills = ClassRegistry::init('SheetRideDetailRidesTransportBills');
        $sheetRideDetailRidesIds = $this->SheetRideDetailRidesTransportBills
            ->find('all',array(
                'conditions' => array(
                    'SheetRideDetailRidesTransportBills.transport_bill_id' => $transportBillId
                ),
                'fields' => 'SheetRideDetailRidesTransportBills.sheet_ride_detail_ride_id'
            ));
        $sheetRidesDetailsIds = array();
        foreach ($sheetRideDetailRidesIds as $id)
        {
            array_push($sheetRidesDetailsIds,
                $id['SheetRideDetailRidesTransportBills']['sheet_ride_detail_ride_id']);
        }
        if ($type == TransportBillTypesEnum::invoice){
            $this->updateMissionsStatusFromBills($sheetRidesDetailsIds,StatusEnum::mission_closed);
        }elseif ($type == TransportBillTypesEnum::credit_note){
            $this->updateMissionsStatusFromBills($sheetRidesDetailsIds,StatusEnum::mission_invoiced);
        }
        $this->deleteRidesDetailsRelationshipsWithTransportBill($transportBillId);
    }

    private function updateMissionsStatusFromBills($sheetRideDetailRideIds = null, $type = null)
    {
        $this->SheetRideDetailRides = ClassRegistry::init('SheetRideDetailRides');
        $this->SheetRideDetailRides->updateAll(
            array('SheetRideDetailRides.status_id' => $type),
            array('SheetRideDetailRides.id' => $sheetRideDetailRideIds)
        );
    }

    private function deleteRidesDetailsRelationshipsWithTransportBill($transportBillId)
    {
        $this->SheetRideDetailRidesTransportBills = ClassRegistry::init('SheetRideDetailRidesTransportBills');
        $this->SheetRideDetailRidesTransportBills->deleteAll(
            array('SheetRideDetailRidesTransportBills.transport_bill_id' => $transportBillId)
        );
    }

}