<?php
App::uses('AppModel', 'Model');

/**
 * Class SaveParcsComponent
 * @package App\Controller\Component
 *
 * @property TransportBillsController|AppController $Controller

 */
class SaveTransportBillsComponent extends Component
{
    public function initialize(Controller $controller)
    {
        parent::initialize($controller); // TODO: Change the autogenerated stub

    }

    public function cutCreditNoteTTCAmountFromInvoiceAmountRemaining($invoiceId,$creditNoteAmount)
    {
        $this->Controller = $this->_Collection->getController();
        if (!empty($invoiceId) && !empty($creditNoteAmount)){
            $invoice = $this->Controller->TransportBill->find('first',array(
                'conditions' => array(
                    'TransportBill.id' => $invoiceId
                )
            ));
            $this->Controller->TransportBill->id = $invoiceId;
            $newInvoiceAmountRemaining = $invoice['TransportBill']['amount_remaining'] - $creditNoteAmount;
            $this->Controller->TransportBill->set(array('amount_remaining' => $newInvoiceAmountRemaining));
            $this->Controller->TransportBill->save();
        }
    }

    public function cutCreditNoteAfterEditTTCAmountFromInvoiceAmountRemaining($oldCreditNote, $newCreditNote){
        $operation = '';
        $ttcDifference = 0;
        $this->Controller = $this->_Collection->getController();
        if ($newCreditNote['TransportBill']['total_ttc'] > $oldCreditNote['TransportBill']['total_ttc'] ){
            $ttcDifference = $newCreditNote['TransportBill']['total_ttc'] - $oldCreditNote['TransportBill']['total_ttc'];
            $operation = '-';
        }elseif ($newCreditNote['TransportBill']['total_ttc'] < $oldCreditNote['TransportBill']['total_ttc']){
            $ttcDifference = $oldCreditNote['TransportBill']['total_ttc'] - $newCreditNote['TransportBill']['total_ttc'];
            $operation = '+';
        }
        $invoice = $this->Controller->TransportBill->find('first',array(
            'conditions' => array(
                'TransportBill.id' => $oldCreditNote['TransportBill']['invoice_id']
            )
        ));
        $invoiceAmountRemaining =  $invoice['TransportBill']['amount_remaining'];
        if ($operation == '+'){
            $invoiceAmountRemaining = $invoiceAmountRemaining + $ttcDifference;
        }elseif($operation == '-'){
            $invoiceAmountRemaining = $invoiceAmountRemaining - $ttcDifference;
        }
        if ($operation != ''){
            $this->Controller->TransportBill->id = $oldCreditNote['TransportBill']['invoice_id'];
            $this->Controller->TransportBill->set(array('amount_remaining' => $invoiceAmountRemaining ));
            $this->Controller->TransportBill->save();
        }
    }

    public function updateRelatedInvoiceAmountRemaining($creditNote)
    {
        $this->Controller = $this->_Collection->getController();

        $invoice = $this->Controller->TransportBill->find('first',array(
            'conditions' => array(
                'TransportBill.id' => $creditNote['TransportBill']['invoice_id']
            )
        ));


        $invoiceAmountRemaining = $invoice['TransportBill']['amount_remaining'];
        $creditNoteTotalTtc = $creditNote['TransportBill']['total_ttc'];
        $newAmountRemaining = $invoiceAmountRemaining + $creditNoteTotalTtc;
        $this->Controller->TransportBill->id = $invoice['TransportBill']['id'];
        $this->Controller->TransportBill->set(array(
            'amount_remaining' => $newAmountRemaining ,
            'has_credit_note' => 0
            ));
        if ($this->Controller->TransportBill->save()){
            $this->updatePaymentStatus($invoice['TransportBill']['id']);
        }

    }

    public function updatePaymentStatus($transportBillId)
    {
        $this->Controller = $this->_Collection->getController();
        $invoice = $this->Controller->TransportBill->find('first',array(
            'conditions' => array(
                'TransportBill.id' => $transportBillId
            )
        ));
        if ($invoice['TransportBill']['total_ttc'] == $invoice['TransportBill']['amount_remaining'] ){
            $statusPayment = 1;
        }elseif ($invoice['TransportBill']['amount_remaining'] == 0){
            $statusPayment = 2;
        }elseif ($invoice['TransportBill']['amount_remaining'] < $invoice['TransportBill']['total_ttc']){
            $statusPayment = 3;
        }
        if (isset($statusPayment)){
            $this->Controller->TransportBill->id = $transportBillId;
            $this->Controller->TransportBill->set(array(
                'status_payment' => $statusPayment ,
            ));
            $this->Controller->TransportBill->save();
        }
    }
}
