<?php
App::uses('AppModel', 'Model');

/**
 * Class SaveParcsComponent
 * @package App\Controller\Component

 */
class SaveParcsComponent extends Component
{
    public function initialize(Controller $controller)
    {
        parent::initialize($controller); // TODO: Change the autogenerated stub

    }
    public function saveParcUserAssociation($parcId, $userId)
    {
        if (!$this->doesParcUserAssociationExist($parcId, $userId)) {
            $this->_Collection->getController()->UserParc->addUserParcs(
                array(
                    0 => $parcId
                ),
                $userId
            );
        }
    }

    public function doesParcUserAssociationExist($parcId, $userId)
    {
        $result = $this->_Collection->getController()->UserParc->getUserParcAssociationByParcIdAndUsersId($parcId, $userId);
        return !empty($result); 
    }
}
