<?php
App::uses('AppModel', 'Model');

/**
 * Class TransportBillDetailedRidesManagementComponent
 * @package App\Controller\Component
 * @property TransportBillDetailedRides $TransportBillDetailedRides
 * @property TransportBillDetailRides $TransportBillDetailRides
 * @property Product $Product
 * @property Parameter $Parameter
 */
class TransportBillDetailedRidesManagementComponent extends Component
{
    public function initialize(Controller $controller)
    {
        parent::initialize($controller); // TODO: Change the autogenerated stub
        $this->TransportBillDetailedRides = ClassRegistry::init('TransportBillDetailedRides');
        $this->Product = ClassRegistry::init('Product');
    }

    public function addTransportBillDetailedRides(
        $transportBillDetailRides = null,
        $reference = null,
        $transportBillId = null,
        $userId = null,
        $type = null,
        $supplierFinal = null,
        $customerOrderValidationMethod = null
    ){
        $this->TransportBillDetailedRides = ClassRegistry::init('TransportBillDetailedRides');
        $this->TransportBillDetailRides = ClassRegistry::init('TransportBillDetailRides');
        $this->Parameter = ClassRegistry::init('Parameter');
        $this->Product = ClassRegistry::init('Product');
        $savedTransportBillDetailRides = $this->TransportBillDetailRides->find('all',
            array(
                'conditions' => array(
                    'TransportBillDetailRides.transport_bill_id' => $transportBillId
                )
            ));
        $save = false ;
        $nbRides = count($savedTransportBillDetailRides);
        for ($i = 0; $i < $nbRides;$i++) {
            $nbTrucks = intval($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['nb_trucks']);
            for ($j = 0;$j < $nbTrucks;$j++){

                $dataToBeSaved = array();
                $product = $this->Product->getProductById($transportBillDetailRides[$i+1]['product_id']);
                $productTypeId = $product['Product']['product_type_id'];
                $relationWithPark = $product['ProductType']['relation_with_park'];
                switch ($productTypeId){
                    case 1 :
                        if (isset($transportBillDetailRides[$i+1]['detail_ride_id'])) {
                            $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validate;
                        } else {
                            $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validatePersonalizedRide;
                        }
                        break;
                    case 3 :
                        $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validateProvision;
                        break;
                    default :
                        $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validateProduct;
                        break;
                }


                $this->TransportBillDetailedRides->create();

                if ($reference != null) {
                    $dataToBeSaved['TransportBillDetailedRides']['reference'] = $reference . '/' . ($j+1);
                }
                $dataToBeSaved['TransportBillDetailedRides']['transport_bill_id'] = $transportBillId;
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_ride'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['type_ride'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_ride'];
                }else {
                    if($relationWithPark==1){
                        $dataToBeSaved['TransportBillDetailedRides']['type_ride'] = 2;
                    }
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_pricing'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['type_pricing'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_pricing'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['tonnage_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['tonnage_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['tonnage_id'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['detail_ride_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['detail_ride_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['detail_ride_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['detail_ride_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['from_customer_order'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['from_customer_order'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['from_customer_order'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['departure_destination_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['departure_destination_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['departure_destination_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['departure_destination_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['arrival_destination_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['arrival_destination_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['arrival_destination_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['arrival_destination_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['car_type_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['car_type_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['car_type_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['car_type_id'] = NULL;
                }

                if (isset($transportBillDetailRides[$i+1]['product_id'])) {
                    $productId = $transportBillDetailRides[$i+1]['product_id'];
                    $usePurchaseBill = $this->Parameter->getCodesParameterVal('use_purchase_bill');
                    if ($usePurchaseBill == 1) {
                        $product = $this->Product->getProductById($productId);
                        $productWithLot = $product['Product']['with_lot'];
                        if ($productWithLot == 1) {
                            $lotId = $transportBillDetailRides[$i+1]['lot_id'];
                        } else {
                            $lotId = $transportBillDetailRides[$i+1]['product_id'];
                        }
                    } else {
                        $lotId = $transportBillDetailRides[$i+1]['product_id'];
                    }
                    $dataToBeSaved['TransportBillDetailedRides']['lot_id'] = $lotId;
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['lot_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['designation'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['designation'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['designation'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['designation'] = NULL;
                }

                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['description'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['description'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['description'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['description'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['observation_order'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['observation_order'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['observation_order'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['observation_order'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['supplier_final_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['supplier_final_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['supplier_final_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['supplier_final_id'] = $supplierFinal;
                }
                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['programming_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['programming_date'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['programming_date'];
                }
                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['charging_time'])){
                    $dataToBeSaved['TransportBillDetailedRides']['charging_time'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['charging_time'];
                }

                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['unloading_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['unloading_date'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['unloading_date'];
                }
                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['start_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['start_date'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['start_date'];
                }
                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['end_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['end_date'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['end_date'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['car_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['car_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['car_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['car_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['nb_hours'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['nb_hours'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['nb_hours'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['nb_hours'] = NULL;
                }
                $dataToBeSaved['TransportBillDetailedRides']['unit_price'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['price_ht'] / $nbTrucks;
                if ($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['delivery_with_return']) {
                    $dataToBeSaved['TransportBillDetailedRides']['delivery_with_return'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['delivery_with_return'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ride_category_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['ride_category_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ride_category_id'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_price'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['type_price'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_price'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['type_price'] = 1;
                }
                $dataToBeSaved['TransportBillDetailedRides']['nb_trucks'] = 1;
                $dataToBeSaved['TransportBillDetailedRides']['price_ht'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['price_ht'] / $nbTrucks;
                $dataToBeSaved['TransportBillDetailedRides']['price_ttc'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['price_ttc'] / $nbTrucks;
                $dataToBeSaved['TransportBillDetailedRides']['tva_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['tva_id'];
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ristourne_val'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['ristourne_val'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ristourne_val'] / $nbTrucks;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ristourne_%'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['ristourne_%'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ristourne_%'];
                }
                // var_dump($type); die();
                switch ($type) {
                    case TransportBillTypesEnum::quote_request :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = StatusEnum::quotation;
                        break;
                    case TransportBillTypesEnum::quote :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = StatusEnum::quotation;
                        break;
                    case TransportBillTypesEnum::order :
                        if($relationWithPark==1){
                            if ($customerOrderValidationMethod == 1) {
                                $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillDetailRideStatusesEnum::not_validated;
                            } else {
                                $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillDetailRideStatusesEnum::not_transmitted;
                            }
                        }else {
                            $dataToBeSaved['TransportBillDetailedRides']['status_id'] = $transportBillDetailRides[$i+1]['status_id'];
                        }

                        break;
                    case TransportBillTypesEnum::pre_invoice :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillTypesEnum::pre_invoice;
                        break;
                    case TransportBillTypesEnum::invoice :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillTypesEnum::invoice;
                        break;

                    case TransportBillTypesEnum::credit_note :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillTypesEnum::credit_note;
                        break;
                }

                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['sheet_ride_detail_ride_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['sheet_ride_detail_ride_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['sheet_ride_detail_ride_id'];
                }
                if ($type == TransportBillTypesEnum::pre_invoice) {
                    $dataToBeSaved['TransportBillDetailedRides']['approved'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['approved'];
                }
                $dataToBeSaved['TransportBillDetailedRides']['transport_bill_detail_ride_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['id'];
                $dataToBeSaved['TransportBillDetailedRides']['user_id'] = $userId;
                $this->TransportBillDetailedRides->save($dataToBeSaved);
            }


            //var_dump($this->TransportBillDetailRides->save($data[$i]));
            //var_dump($this->TransportBillDetailRides->validationErrors);die();


        }
        /*if($type != TransportBillTypesEnum::order){

            if($this->TransportBillDetailRides->saveAll($data) ) {
                $save = true;
            }

        }*/
        return $save;
    }

    public function createDateFromDate($data, $inputName)
    {
        if (isset($data[$inputName]) && !empty($data[$inputName])) {
            $data[$inputName] = DateTime::createFromFormat('d/m/Y',
                $data[$inputName]);
            if ($data[$inputName] instanceof DateTime) {
                $data[$inputName]= $data[$inputName]->format('Y-m-d');
            } else {
                $data[$inputName] = null;
            }
        } else {
            $data[$inputName] = null;
        }
        return $data[$inputName];
    }

    public function createDatetimeFromDatetime($data, $inputName)
    {
        if (isset($data[$inputName]) && !empty($data[$inputName])) {
            $data[$inputName] = DateTime::createFromFormat('d/m/Y H:i',
                $data[$inputName]);

            if ($data[$inputName] instanceof DateTime) {
                $data[$inputName] = $data[$inputName]->format('Y-m-d-H-i-s');
            } else {
                $data[$inputName] = null;
            }
        } else {
            $data[$inputName] = null;
        }
        return $data[$inputName];
    }

    public function editDetailedRide($ride ,$transportBillId)
    {
        $this->TransportBillDetailedRides = ClassRegistry::init('TransportBillDetailedRides');
        $detailedRides = $this->TransportBillDetailedRides->find('all',
            array(
                'conditions' => array(
                    'TransportBillDetailedRides.transport_bill_id' => $transportBillId,
                    'TransportBillDetailedRides.transport_bill_detail_ride_id' => $ride['id'],
                )
            ));

        foreach ($detailedRides as $detailedRide) {
            $this->TransportBillDetailedRides->id = $detailedRide['TransportBillDetailedRides']['id'];
            $this->TransportBillDetailedRides->set(
                array(
                    'unit_price' => $ride['unit_price'],
                    'price_ht' => $ride['price_ht'],
                    'price_ttc' => floatval($ride['price_ht']) * 1.19,
                    'programming_date' => $ride['programming_date'],
                    'unloading_date' => $ride['unloading_date'],
                    'charging_time' => $ride['charging_time'],
                    'departure_destination_id' => $ride['departure_destination_id'],
                    'car_type_id' => $ride['car_type_id'],
                    'arrival_destination_id' => $ride['arrival_destination_id'],
                    'supplier_final_id' => $ride['supplier_final_id'],
                    'designation' => $ride['designation'],
                    'delivery_with_return' => isset($ride['delivery_with_return']) ? $ride['delivery_with_return'] : 1 ,
                    'ristourne_%' => $ride['ristourne_%'],
                    'ristourne_val' => $ride['ristourne_val'],
                    'tva_id' => $ride['tva_id'],
                    'observation_order' => $ride['observation_order'],
                )
            );
            $this->TransportBillDetailedRides->save();
        }

    }

    public function addTransportBillDetailedRidesFromTransformation(
        $transportBillDetailRides = null,
        $reference = null,
        $transportBillId = null,
        $userId = null,
        $type = null,
        $supplierFinal = null,
        $customerOrderValidationMethod = null
    ){
        $this->TransportBillDetailedRides = ClassRegistry::init('TransportBillDetailedRides');
        $this->TransportBillDetailRides = ClassRegistry::init('TransportBillDetailRides');
        $this->Parameter = ClassRegistry::init('Parameter');
        $this->Product = ClassRegistry::init('Product');
        $savedTransportBillDetailRides = $this->TransportBillDetailRides->find('all',
            array(
                'conditions' => array(
                    'TransportBillDetailRides.transport_bill_id' => $transportBillId
                )
            ));
        $save = false ;
        $nbRides = count($savedTransportBillDetailRides);
        for ($i = 0; $i < $nbRides;$i++) {
            $nbTrucks = intval($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['nb_trucks']);
            for ($j = 0;$j < $nbTrucks;$j++){

                $dataToBeSaved = array();
                $product = $this->Product->getProductById($transportBillDetailRides[$i]['product_id']);
                $productTypeId = $product['Product']['product_type_id'];
                $relationWithPark = $product['ProductType']['relation_with_park'];
                switch ($productTypeId){
                    case 1 :
                        if (isset($transportBillDetailRides[$i+1]['detail_ride_id'])) {
                            $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validate;
                        } else {
                            $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validatePersonalizedRide;
                        }
                        break;
                    case 3 :
                        $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validateProvision;
                        break;
                    default :
                        $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validateProduct;
                        break;
                }


                $this->TransportBillDetailedRides->create();

                if ($reference != null) {
                    $dataToBeSaved['TransportBillDetailedRides']['reference'] = $reference . '/' . ($j+1);
                }
                $dataToBeSaved['TransportBillDetailedRides']['transport_bill_id'] = $transportBillId;
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_ride'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['type_ride'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_ride'];
                }else {
                    if($relationWithPark==1){
                        $dataToBeSaved['TransportBillDetailedRides']['type_ride'] = 2;
                    }
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_pricing'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['type_pricing'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_pricing'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['tonnage_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['tonnage_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['tonnage_id'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['detail_ride_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['detail_ride_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['detail_ride_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['detail_ride_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['from_customer_order'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['from_customer_order'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['from_customer_order'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['departure_destination_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['departure_destination_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['departure_destination_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['departure_destination_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['arrival_destination_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['arrival_destination_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['arrival_destination_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['arrival_destination_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['car_type_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['car_type_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['car_type_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['car_type_id'] = NULL;
                }

                if (isset($transportBillDetailRides[$i+1]['product_id'])) {
                    $productId = $transportBillDetailRides[$i+1]['product_id'];
                    $usePurchaseBill = $this->Parameter->getCodesParameterVal('use_purchase_bill');
                    if ($usePurchaseBill == 1) {
                        $product = $this->Product->getProductById($productId);
                        $productWithLot = $product['Product']['with_lot'];
                        if ($productWithLot == 1) {
                            $lotId = $transportBillDetailRides[$i+1]['lot_id'];
                        } else {
                            $lotId = $transportBillDetailRides[$i+1]['product_id'];
                        }
                    } else {
                        $lotId = $transportBillDetailRides[$i+1]['product_id'];
                    }
                    $dataToBeSaved['TransportBillDetailedRides']['lot_id'] = $lotId;
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['lot_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['designation'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['designation'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['designation'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['designation'] = NULL;
                }

                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['description'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['description'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['description'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['description'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['observation_order'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['observation_order'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['observation_order'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['observation_order'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['supplier_final_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['supplier_final_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['supplier_final_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['supplier_final_id'] = $supplierFinal;
                }
                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['programming_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['programming_date'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['programming_date'];
                }
                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['charging_time'])){
                    $dataToBeSaved['TransportBillDetailedRides']['charging_time'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['charging_time'];
                }

                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['unloading_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['unloading_date'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['unloading_date'];
                }
                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['start_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['start_date'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['start_date'];
                }
                if(isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['end_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['end_date'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['end_date'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['car_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['car_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['car_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['car_id'] = NULL;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['nb_hours'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['nb_hours'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['nb_hours'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['nb_hours'] = NULL;
                }
                $dataToBeSaved['TransportBillDetailedRides']['unit_price'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['price_ht'] / $nbTrucks;
                if ($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['delivery_with_return']) {
                    $dataToBeSaved['TransportBillDetailedRides']['delivery_with_return'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['delivery_with_return'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ride_category_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['ride_category_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ride_category_id'];
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_price'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['type_price'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['type_price'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['type_price'] = 1;
                }
                $dataToBeSaved['TransportBillDetailedRides']['nb_trucks'] = 1;
                $dataToBeSaved['TransportBillDetailedRides']['price_ht'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['price_ht'] / $nbTrucks;
                $dataToBeSaved['TransportBillDetailedRides']['price_ttc'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['price_ttc'] / $nbTrucks;
                $dataToBeSaved['TransportBillDetailedRides']['tva_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['tva_id'];
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ristourne_val'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['ristourne_val'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ristourne_val'] / $nbTrucks;
                }
                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ristourne_%'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['ristourne_%'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['ristourne_%'];
                }
                // var_dump($type); die();
                switch ($type) {
                    case TransportBillTypesEnum::quote_request :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = StatusEnum::quotation;
                        break;
                    case TransportBillTypesEnum::quote :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = StatusEnum::quotation;
                        break;
                    case TransportBillTypesEnum::order :
                        if($relationWithPark==1){
                            if ($customerOrderValidationMethod == 1) {
                                $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillDetailRideStatusesEnum::not_validated;
                            } else {
                                $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillDetailRideStatusesEnum::not_transmitted;
                            }
                        }else {
                            $dataToBeSaved['TransportBillDetailedRides']['status_id'] = $transportBillDetailRides[$i]['status_id'];
                        }

                        break;
                    case TransportBillTypesEnum::pre_invoice :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillTypesEnum::pre_invoice;
                        break;
                    case TransportBillTypesEnum::invoice :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillTypesEnum::invoice;
                        break;

                    case TransportBillTypesEnum::credit_note :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillTypesEnum::credit_note;
                        break;
                }

                if (isset($savedTransportBillDetailRides[$i]['TransportBillDetailRides']['sheet_ride_detail_ride_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['sheet_ride_detail_ride_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['sheet_ride_detail_ride_id'];
                }
                if ($type == TransportBillTypesEnum::pre_invoice) {
                    $dataToBeSaved['TransportBillDetailedRides']['approved'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['approved'];
                }
                $dataToBeSaved['TransportBillDetailedRides']['transport_bill_detail_ride_id'] = $savedTransportBillDetailRides[$i]['TransportBillDetailRides']['id'];
                $dataToBeSaved['TransportBillDetailedRides']['user_id'] = $userId;
                $this->TransportBillDetailedRides->save($dataToBeSaved);
            }


            //var_dump($this->TransportBillDetailRides->save($data[$i]));
            //var_dump($this->TransportBillDetailRides->validationErrors);die();


        }
        /*if($type != TransportBillTypesEnum::order){

            if($this->TransportBillDetailRides->saveAll($data) ) {
                $save = true;
            }

        }*/
        return $save;
    }

    public function addDifferenceTransportBillDetailedRides($transportBillDetailRides, $transportBillId ,$type,$userId = null)
    {
        $this->Parameter = ClassRegistry::init('Parameter');
        $this->Product = ClassRegistry::init('Product');
        $this->TransportBillDetailedRides = ClassRegistry::init('TransportBillDetailedRides');
        $detailedRides = $this->TransportBillDetailedRides->find('all',
            array(
                'conditions' => array(
                    'TransportBillDetailedRides.transport_bill_id' => $transportBillId,
                    'TransportBillDetailedRides.transport_bill_detail_ride_id' => $transportBillDetailRides['id'],
                )
            ));
        $newNbTrucks = intval($transportBillDetailRides['nb_trucks']);
        $detailedRidesCount = count($detailedRides);
        $difference = $newNbTrucks - $detailedRidesCount;
        if ($difference > 0){
            for ($j = 0;$j < $difference;$j++){

                $dataToBeSaved = array();
                $product = $this->Product->getProductById($transportBillDetailRides['product_id']);
                $productTypeId = $product['Product']['product_type_id'];
                $relationWithPark = $product['ProductType']['relation_with_park'];
                switch ($productTypeId){
                    case 1 :
                        if (isset($transportBillDetailRides['detail_ride_id'])) {
                            $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validate;
                        } else {
                            $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validatePersonalizedRide;
                        }
                        break;
                    case 3 :
                        $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validateProvision;
                        break;
                    default :
                        $this->TransportBillDetailedRides->validate = $this->TransportBillDetailedRides->validateProduct;
                        break;
                }


                $this->TransportBillDetailedRides->create();


                    $dataToBeSaved['TransportBillDetailedRides']['reference'] = $transportBillDetailRides['reference'];

                $dataToBeSaved['TransportBillDetailedRides']['transport_bill_id'] = $transportBillId;
                if (isset($transportBillDetailRides['type_ride'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['type_ride'] = $transportBillDetailRides['type_ride'];
                }else {
                    if($relationWithPark==1){
                        $dataToBeSaved['TransportBillDetailedRides']['type_ride'] = 2;
                    }
                }
                if (isset($transportBillDetailRides['type_pricing'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['type_pricing'] = $transportBillDetailRides['type_pricing'];
                }
                if (isset($transportBillDetailRides['tonnage_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['tonnage_id'] = $transportBillDetailRides['tonnage_id'];
                }
                if (isset($transportBillDetailRides['detail_ride_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['detail_ride_id'] = $transportBillDetailRides['detail_ride_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['detail_ride_id'] = NULL;
                }
                if (isset($transportBillDetailRides['from_customer_order'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['from_customer_order'] = $transportBillDetailRides['from_customer_order'];
                }
                if (isset($transportBillDetailRides['departure_destination_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['departure_destination_id'] = $transportBillDetailRides['departure_destination_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['departure_destination_id'] = NULL;
                }
                if (isset($transportBillDetailRides['arrival_destination_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['arrival_destination_id'] = $transportBillDetailRides['arrival_destination_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['arrival_destination_id'] = NULL;
                }
                if (isset($transportBillDetailRides['car_type_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['car_type_id'] = $transportBillDetailRides['car_type_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['car_type_id'] = NULL;
                }

                if (isset($transportBillDetailRides['product_id'])) {
                    $productId = $transportBillDetailRides['product_id'];
                    $usePurchaseBill = $this->Parameter->getCodesParameterVal('use_purchase_bill');
                    if ($usePurchaseBill == 1) {
                        $product = $this->Product->getProductById($productId);
                        $productWithLot = $product['Product']['with_lot'];
                        if ($productWithLot == 1) {
                            $lotId = $transportBillDetailRides['lot_id'];
                        } else {
                            $lotId = $transportBillDetailRides['product_id'];
                        }
                    } else {
                        $lotId = $transportBillDetailRides['product_id'];
                    }
                    $dataToBeSaved['TransportBillDetailedRides']['lot_id'] = $lotId;
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['lot_id'] = NULL;
                }
                if (isset($transportBillDetailRides['designation'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['designation'] = $transportBillDetailRides['designation'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['designation'] = NULL;
                }

                if (isset($transportBillDetailRides['description'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['description'] = $transportBillDetailRides['description'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['description'] = NULL;
                }
                if (isset($transportBillDetailRides['observation_order'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['observation_order'] = $transportBillDetailRides['observation_order'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['observation_order'] = NULL;
                }
                if (isset($transportBillDetailRides['supplier_final_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['supplier_final_id'] = $transportBillDetailRides['supplier_final_id'];
                }
                if(isset($transportBillDetailRides['programming_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['programming_date'] = $transportBillDetailRides['programming_date'];
                }
                if(isset($transportBillDetailRides['charging_time'])){
                    $dataToBeSaved['TransportBillDetailedRides']['charging_time'] = $transportBillDetailRides['charging_time'];
                }

                if(isset($transportBillDetailRides['unloading_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['unloading_date'] = $transportBillDetailRides['unloading_date'];
                }
                if(isset($transportBillDetailRides['start_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['start_date'] = $transportBillDetailRides['start_date'];
                }
                if(isset($transportBillDetailRides['end_date'])){
                    $dataToBeSaved['TransportBillDetailedRides']['end_date'] = $transportBillDetailRides['end_date'];
                }
                if (isset($transportBillDetailRides['car_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['car_id'] = $transportBillDetailRides['car_id'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['car_id'] = NULL;
                }
                if (isset($transportBillDetailRides['nb_hours'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['nb_hours'] = $transportBillDetailRides['nb_hours'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['nb_hours'] = NULL;
                }
                $dataToBeSaved['TransportBillDetailedRides']['unit_price'] = $transportBillDetailRides['price_ht'] / $newNbTrucks;
                if ($transportBillDetailRides['delivery_with_return']) {
                    $dataToBeSaved['TransportBillDetailedRides']['delivery_with_return'] = $transportBillDetailRides['delivery_with_return'];
                }
                if (isset($transportBillDetailRides['ride_category_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['ride_category_id'] = $transportBillDetailRides['ride_category_id'];
                }
                if (isset($transportBillDetailRides['type_price'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['type_price'] = $transportBillDetailRides['type_price'];
                } else {
                    $dataToBeSaved['TransportBillDetailedRides']['type_price'] = 1;
                }
                $dataToBeSaved['TransportBillDetailedRides']['nb_trucks'] = 1;
                $dataToBeSaved['TransportBillDetailedRides']['price_ht'] = $transportBillDetailRides['price_ht'] / $newNbTrucks;
                $dataToBeSaved['TransportBillDetailedRides']['price_ttc'] = $transportBillDetailRides['price_ttc'] / $newNbTrucks;
                $dataToBeSaved['TransportBillDetailedRides']['tva_id'] = $transportBillDetailRides['tva_id'];
                if (isset($transportBillDetailRides['ristourne_val'])) {
                    if ($newNbTrucks>0){
                        $dataToBeSaved['TransportBillDetailedRides']['ristourne_val'] = $transportBillDetailRides['ristourne_val'] / $newNbTrucks;
                    }
                }
                if (isset($transportBillDetailRides['TransportBillDetailRides']['ristourne_%'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['ristourne_%'] = $transportBillDetailRides['TransportBillDetailRides']['ristourne_%'];
                }
                // var_dump($type); die();
                switch ($type) {
                    case TransportBillTypesEnum::quote_request :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = StatusEnum::quotation;
                        break;
                    case TransportBillTypesEnum::quote :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = StatusEnum::quotation;
                        break;
                    case TransportBillTypesEnum::order :
                        if($relationWithPark==1){

                                $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillDetailRideStatusesEnum::not_transmitted;

                        }else {
                            $dataToBeSaved['TransportBillDetailedRides']['status_id'] = $transportBillDetailRides['status_id'];
                        }

                        break;
                    case TransportBillTypesEnum::pre_invoice :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillTypesEnum::pre_invoice;
                        break;
                    case TransportBillTypesEnum::invoice :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillTypesEnum::invoice;
                        break;

                    case TransportBillTypesEnum::credit_note :
                        $dataToBeSaved['TransportBillDetailedRides']['status_id'] = TransportBillTypesEnum::credit_note;
                        break;
                }

                if (isset($transportBillDetailRides['sheet_ride_detail_ride_id'])) {
                    $dataToBeSaved['TransportBillDetailedRides']['sheet_ride_detail_ride_id'] = $transportBillDetailRides['sheet_ride_detail_ride_id'];
                }
                if ($type == TransportBillTypesEnum::pre_invoice) {
                    $dataToBeSaved['TransportBillDetailedRides']['approved'] = $transportBillDetailRides['approved'];
                }
                $dataToBeSaved['TransportBillDetailedRides']['transport_bill_detail_ride_id'] = $transportBillDetailRides['id'];
                $dataToBeSaved['TransportBillDetailedRides']['user_id'] = $userId;
                $this->TransportBillDetailedRides->save($dataToBeSaved);
            }
        }
    }
}

